apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-rollouts
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/apps/umbrella-rollouts
    repoURL: https://github.com/vhsanche/kube.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true