apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/apps/sonarqube/dev
    repoURL: https://github.com/vhsanche/kube.git
    targetRevision: dev-jeff
  syncPolicy:
    automated:
      prune: true
      selfHeal: true